In [ ]:
ANS-1

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types of both variables
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))



Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>



ANS-2


import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in 'list_'
print("Data type of each element in 'list_':")
for element in list_:
    print(f"{element}: {type(element)}")

# Print the data type of each element in 'array_list'
print("\nData type of each element in 'array_list':")
for element in array_list:
    print(f"{element}: {type(element)}")

    
    
   OUTPUT 
    
    
    Data type of each element in 'list_':
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data type of each element in 'array_list':
1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>



ANS-3


import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print the data type of each element in 'list_'
print("Data type of each element in 'list_':")
for element in list_:
    print(f"{element}: {type(element)}")

# Print the data type of each element in 'array_list'
print("\nData type of each element in 'array_list':")
for element in array_list:
    print(f"{element}: {type(element)}")

    
    
    OUTPUT
    
    
    Data type of each element in 'list_':
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data type of each element in 'array_list':
1: <class 'numpy.int64'>
2: <class 'numpy.int64'>
3: <class 'numpy.int64'>
4: <class 'numpy.int64'>
5: <class 'numpy.int64'>




ANS-4


import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape

# Find the size of num_array
size = num_array.size

# Print the characteristics
print("Shape of num_array:", shape)
print("Size of num_array:", size)



OUTPUT


Shape of num_array: (2, 3)
Size of num_array: 6


ANS-5






import numpy as np

# Create a 3x3 matrix containing zeros
zeros_matrix = np.zeros((3, 3))

# Print the matrix
print(zeros_matrix)




OUTPUT

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



ANS-6


import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the matrix
print(identity_matrix)


OUTPUT


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]





